const { Router } = require('express');
const ctrl = require('../controllers/review.controller');
const { authenticate } = require('../../shared/middleware/auth.middleware');
const router = Router();
router.post('/', authenticate, ctrl.createReview);
router.get('/course/:courseId', ctrl.getReviewsByCourse);
router.get('/course/:courseId/stats', ctrl.getCourseStats);
router.put('/:reviewId', authenticate, ctrl.updateReview);
router.delete('/:reviewId', authenticate, ctrl.deleteReview);
module.exports = router;
